/**
 * This file was automatically generated by Nexus 0.11.7
 * Do not make changes to this file directly
 */


import { core } from "nexus"
declare global {
  interface NexusGenCustomDefinitionMethods<TypeName extends string> {
    emailAddress<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "EmailAddress";
    jwt<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JWT";
    postalCode<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "PostalCode";
    sensitiveString<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "SensitiveString";
    url<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "URL";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AddPaymentCredentialInput: { // input type
    card_association: string; // String!
    last_four_digits: number; // Int!
    stripe_token: string; // String!
  }
  AddShippingAddressInput: { // input type
    address_line_1: string; // String!
    address_line_2?: string | null; // String
    address_line_3?: string | null; // String
    city: string; // String!
    country: string; // String!
    postal_code: string; // PostalCode!
    region?: string | null; // String
  }
  AddToSavedCartInput: { // input type
    amount: number; // Int!
    book_id: string; // String!
  }
  AddToShoppingCartInput: { // input type
    amount: number; // Int!
    book_id: string; // String!
  }
  BookDetailsInput: { // input type
    id: string; // ID!
  }
  EditUserInput: { // input type
    email: string; // EmailAddress!
    first_name: string; // String!
    last_name: string; // String!
    selected_shipping_address_id: string; // ID!
    username: string; // String!
  }
  LogInInput: { // input type
    email: string; // EmailAddress!
    password: string; // SensitiveString!
  }
  RemoveFromSavedCartInput: { // input type
    item_id: string; // String!
  }
  RemoveFromShoppingCartInput: { // input type
    item_id: string; // String!
  }
  RemovePaymentCredentialInput: { // input type
    payment_credential_id: string; // ID!
  }
  RemoveShippingAddressInput: { // input type
    shipping_address_id: string; // ID!
  }
  SetDefaultShippingAddressInput: { // input type
    address_id: string; // ID!
  }
  SignUpInput: { // input type
    address_line_1: string; // String!
    address_line_2?: string | null; // String
    address_line_3?: string | null; // String
    city: string; // String!
    country: string; // String!
    email: string; // EmailAddress!
    first_name: string; // String!
    last_name: string; // String!
    password: string; // SensitiveString!
    postal_code: string; // PostalCode!
    region?: string | null; // String
    username: string; // String!
  }
  SortedBooksInput: { // input type
    field_to_sort_by: string; // String!
    sort_direction: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenRootTypes {
  Author: { // root type
    bio: string; // String!
    first_name: string; // String!
    id: string; // ID!
    last_name: string; // String!
  }
  Book: { // root type
    cover: string; // URL!
    description: string; // String!
    genre: string; // String!
    id: string; // ID!
    isbn: string; // String!
    price: number; // Float!
    publish_year: number; // Int!
    title: string; // String!
  }
  Mutation: {};
  PaymentCredential: { // root type
    card_association: string; // String!
    id: string; // ID!
    last_four_digits: number; // Int!
  }
  Query: {};
  SavedCart: { // root type
    id: string; // ID!
  }
  SavedCartItem: { // root type
    amount: number; // Int!
    id: string; // ID!
  }
  ShippingAddress: { // root type
    address_line_1: string; // String!
    address_line_2?: string | null; // String
    address_line_3?: string | null; // String
    city: string; // String!
    country: string; // String!
    id: string; // ID!
    is_default: boolean; // Boolean!
    postal_code: string; // PostalCode!
    region?: string | null; // String
  }
  ShoppingCart: { // root type
    id: string; // ID!
  }
  ShoppingCartItem: { // root type
    amount: number; // Int!
    id: string; // ID!
  }
  User: { // root type
    email: string; // EmailAddress!
    first_name: string; // String!
    id: string; // ID!
    last_name: string; // String!
    username: string; // String!
  }
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  EmailAddress: string;
  JWT: { id: ID };
  PostalCode: string;
  SensitiveString: string;
  URL: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  AddPaymentCredentialInput: NexusGenInputs['AddPaymentCredentialInput'];
  AddShippingAddressInput: NexusGenInputs['AddShippingAddressInput'];
  AddToSavedCartInput: NexusGenInputs['AddToSavedCartInput'];
  AddToShoppingCartInput: NexusGenInputs['AddToShoppingCartInput'];
  BookDetailsInput: NexusGenInputs['BookDetailsInput'];
  EditUserInput: NexusGenInputs['EditUserInput'];
  LogInInput: NexusGenInputs['LogInInput'];
  RemoveFromSavedCartInput: NexusGenInputs['RemoveFromSavedCartInput'];
  RemoveFromShoppingCartInput: NexusGenInputs['RemoveFromShoppingCartInput'];
  RemovePaymentCredentialInput: NexusGenInputs['RemovePaymentCredentialInput'];
  RemoveShippingAddressInput: NexusGenInputs['RemoveShippingAddressInput'];
  SetDefaultShippingAddressInput: NexusGenInputs['SetDefaultShippingAddressInput'];
  SignUpInput: NexusGenInputs['SignUpInput'];
  SortedBooksInput: NexusGenInputs['SortedBooksInput'];
}

export interface NexusGenFieldTypes {
  Author: { // field return type
    bio: string; // String!
    books: NexusGenRootTypes['Book'][]; // [Book!]!
    first_name: string; // String!
    id: string; // ID!
    last_name: string; // String!
  }
  Book: { // field return type
    author: NexusGenRootTypes['Author']; // Author!
    cover: string; // URL!
    description: string; // String!
    genre: string; // String!
    id: string; // ID!
    isbn: string; // String!
    price: number; // Float!
    publish_year: number; // Int!
    title: string; // String!
  }
  Mutation: { // field return type
    add_payment_credential: NexusGenRootTypes['PaymentCredential']; // PaymentCredential!
    add_shipping_address: NexusGenRootTypes['ShippingAddress']; // ShippingAddress!
    add_to_saved_cart: NexusGenRootTypes['SavedCartItem']; // SavedCartItem!
    add_to_shopping_cart: NexusGenRootTypes['ShoppingCartItem']; // ShoppingCartItem!
    checkout_user: NexusGenRootTypes['ShoppingCart']; // ShoppingCart!
    edit_user: NexusGenRootTypes['User']; // User!
    log_in: { id: ID }; // JWT!
    remove_from_saved_cart: NexusGenRootTypes['SavedCart']; // SavedCart!
    remove_from_shopping_cart: NexusGenRootTypes['ShoppingCart']; // ShoppingCart!
    remove_payment_credential: NexusGenRootTypes['PaymentCredential']; // PaymentCredential!
    remove_shipping_address: NexusGenRootTypes['ShippingAddress']; // ShippingAddress!
    save_shopping_cart: NexusGenRootTypes['SavedCart']; // SavedCart!
    set_default_shipping_address: NexusGenRootTypes['ShippingAddress']; // ShippingAddress!
    sign_up: { id: ID }; // JWT!
    unsave_saved_cart: NexusGenRootTypes['ShoppingCart']; // ShoppingCart!
  }
  PaymentCredential: { // field return type
    card_association: string; // String!
    id: string; // ID!
    last_four_digits: number; // Int!
  }
  Query: { // field return type
    book_details: NexusGenRootTypes['Book']; // Book!
    hello_world: string; // String!
    sorted_books: NexusGenRootTypes['Book'][]; // [Book!]!
    viewer: NexusGenRootTypes['User']; // User!
  }
  SavedCart: { // field return type
    id: string; // ID!
    items: NexusGenRootTypes['SavedCartItem'][]; // [SavedCartItem!]!
  }
  SavedCartItem: { // field return type
    amount: number; // Int!
    book: NexusGenRootTypes['Book']; // Book!
    id: string; // ID!
  }
  ShippingAddress: { // field return type
    address_line_1: string; // String!
    address_line_2: string | null; // String
    address_line_3: string | null; // String
    city: string; // String!
    country: string; // String!
    id: string; // ID!
    is_default: boolean; // Boolean!
    postal_code: string; // PostalCode!
    region: string | null; // String
  }
  ShoppingCart: { // field return type
    id: string; // ID!
    items: NexusGenRootTypes['ShoppingCartItem'][]; // [ShoppingCartItem!]!
  }
  ShoppingCartItem: { // field return type
    amount: number; // Int!
    book: NexusGenRootTypes['Book']; // Book!
    id: string; // ID!
  }
  User: { // field return type
    email: string; // EmailAddress!
    first_name: string; // String!
    id: string; // ID!
    last_name: string; // String!
    payment_credentials: NexusGenRootTypes['PaymentCredential'][]; // [PaymentCredential!]!
    saved_cart: NexusGenRootTypes['SavedCart']; // SavedCart!
    shipping_addresses: NexusGenRootTypes['ShippingAddress'][]; // [ShippingAddress!]!
    shopping_cart: NexusGenRootTypes['ShoppingCart']; // ShoppingCart!
    username: string; // String!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    add_payment_credential: { // args
      input: NexusGenInputs['AddPaymentCredentialInput']; // AddPaymentCredentialInput!
    }
    add_shipping_address: { // args
      input: NexusGenInputs['AddShippingAddressInput']; // AddShippingAddressInput!
    }
    add_to_saved_cart: { // args
      input: NexusGenInputs['AddToSavedCartInput']; // AddToSavedCartInput!
    }
    add_to_shopping_cart: { // args
      input: NexusGenInputs['AddToShoppingCartInput']; // AddToShoppingCartInput!
    }
    edit_user: { // args
      input: NexusGenInputs['EditUserInput']; // EditUserInput!
    }
    log_in: { // args
      input: NexusGenInputs['LogInInput']; // LogInInput!
    }
    remove_from_saved_cart: { // args
      input: NexusGenInputs['RemoveFromSavedCartInput']; // RemoveFromSavedCartInput!
    }
    remove_from_shopping_cart: { // args
      input: NexusGenInputs['RemoveFromShoppingCartInput']; // RemoveFromShoppingCartInput!
    }
    remove_payment_credential: { // args
      input: NexusGenInputs['RemovePaymentCredentialInput']; // RemovePaymentCredentialInput!
    }
    remove_shipping_address: { // args
      input: NexusGenInputs['RemoveShippingAddressInput']; // RemoveShippingAddressInput!
    }
    set_default_shipping_address: { // args
      input: NexusGenInputs['SetDefaultShippingAddressInput']; // SetDefaultShippingAddressInput!
    }
    sign_up: { // args
      input: NexusGenInputs['SignUpInput']; // SignUpInput!
    }
  }
  Query: {
    book_details: { // args
      input: NexusGenInputs['BookDetailsInput']; // BookDetailsInput!
    }
    sorted_books: { // args
      input: NexusGenInputs['SortedBooksInput']; // SortedBooksInput!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Author" | "Book" | "Mutation" | "PaymentCredential" | "Query" | "SavedCart" | "SavedCartItem" | "ShippingAddress" | "ShoppingCart" | "ShoppingCartItem" | "User";

export type NexusGenInputNames = "AddPaymentCredentialInput" | "AddShippingAddressInput" | "AddToSavedCartInput" | "AddToShoppingCartInput" | "BookDetailsInput" | "EditUserInput" | "LogInInput" | "RemoveFromSavedCartInput" | "RemoveFromShoppingCartInput" | "RemovePaymentCredentialInput" | "RemoveShippingAddressInput" | "SetDefaultShippingAddressInput" | "SignUpInput" | "SortedBooksInput";

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "EmailAddress" | "Float" | "ID" | "Int" | "JWT" | "PostalCode" | "SensitiveString" | "String" | "URL";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: {};
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}